name: Plan Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target: # This workflow has permissions on the repo, do NOT run code from PRs in this workflow. See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    types:
      - labeled
      - unlabeled

concurrency:
  group: plan-release # only the latest one of these should ever be running
  cancel-in-progress: true

jobs:
  should-run-release-plan-prepare:
    name: Should we run release-plan prepare?
    runs-on: ubuntu-latest
    outputs:
      should-prepare: ${{ steps.should-prepare.outputs.should-prepare }}

    steps:
      - name: Check if we should prepare a release
        uses: release-plan/actions/should-prepare-release@v1
        with:
          ref: 'main'
        id: should-prepare

  create-prepare-release-pr:
    name: Create Prepare Release PR
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: should-run-release-plan-prepare
    permissions:
      contents: write
      issues: read
      pull-requests: write
    if: needs.should-run-release-plan-prepare.outputs.should-prepare == 'true'
    steps:
      - name: Run release-plan prepare
        uses: release-plan/actions/prepare@v1
        with:
          ref: 'main'
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        id: explanation

      - name: Generate commit message
        run: node .github/release-commit-message.js >> "$GITHUB_OUTPUT"
        id: commit-message

      - name: Generate Access Token
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Prepare Release PR
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: ${{ steps.commit-message.outputs.COMMIT_MESSAGE }}
          labels: 'internal'
          sign-commits: true
          branch: release-preview
          draft: true
          title: ${{ steps.commit-message.outputs.COMMIT_MESSAGE }}
          token: ${{ steps.generate-token.outputs.token }}
          body: |
            Merging this PR will create a GitHub release and publish the package(s) to npm.

            This PR is a preview of the release that [release-plan](https://github.com/embroider-build/release-plan) has prepared. To release you should just merge this PR üëç

            -----------------------------------------

            ${{ steps.explanation.outputs.text }}
